# Generated by Django 4.0.5 on 2022-06-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sait', '0003_alter_link_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
