# Generated by Django 4.0.5 on 2022-06-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sait', '0004_rename_owner_room_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='owner_name',
            field=models.CharField(default='objects', editable=False, max_length=50),
        ),
    ]
