# Generated by Django 4.0.5 on 2022-06-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sait', '0005_room_owner_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='owner_name',
        ),
    ]
