# Generated by Django 4.0.5 on 2022-06-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sait', '0006_remove_room_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='tg_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='link',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
    ]
