# Generated by Django 4.0.5 on 2022-06-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sait', '0007_alter_link_tg_name_alter_link_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='tg_name',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='link',
            name='user_id',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
