# Generated by Django 4.0.5 on 2022-06-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sait', '0009_alter_link_tg_name_alter_link_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='password_room',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
