# Generated by Django 4.0.5 on 2022-07-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sait', '0011_alter_room_name_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='password_room',
            field=models.CharField(max_length=50),
        ),
    ]
