version: '3.3'

services:
  django:
    container_name: back_django
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    expose:
      - 8000

  frontend:
    image: nginx:1.13
    build: ./frontend
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d

  tg_bot:
    container_name: bot
    build: .
    command: python run_bot.py
