name: docker CI

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mysite
    steps:
      - uses: actions/checkout@v3
      - name: start docker
        run: docker-compose up -d