name: docker CI

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./mysite

    steps:
      - uses: actions/checkout@v3
      - name: go to the /mysite
        run: ls -R
        working-directory: ${{env.working-directory}}
#      - name: ls
#        run: ls
      - name: build
        run: docker-compose up --build
      - name: start docker
        run: docker-compose up -d