name: docker CI

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: go to the /mysite
        run: cd mysite/
      - name: ls
        run: ls
      - name: start docker
        run: docker-compose up -d